### ISSUE TITLE
How does one create a BigInteger from an integer?

### ISSUE THREAD

**Issue by jcalfee** [cryptocoinjs/bigi#19]
Until we have a constructor: https://github.com/cryptocoinjs/bigi/issues/18
... or a `fromInt` method, what is the best way to create a BigInteger from a number (even one with a decimal place)? 

Here is my work-around, but it produced a number that was much too large in the second case:

```
BigInteger("11").toString() == "11"
BigInteger("1.1").toString() == "11"
```

Both lines return `true`

**Comment by jprichardson** [comment]
I realize that it's kinda clunky, but you have to convert it to a string. Despite the fact that `BigInteger` has two methods `fromInt` and `fromInteger`, they are not exposed. Probably due to some legacy reason.

So:

```js
var assert = require('assert')

var MAX_INT = Math.pow(2, 53)
assert.equal(MAX_INT.toString(10), (new BigInteger(MAX_INT.toString())).toString(10))
```

Regarding:

```js
BigInteger("1.1").toString() == "11"
```

This won't work since this library is for integers only not floating point. So that won't ever work with `BigInteger`.

My long-term intent is to switch to https://github.com/indutny/bn.js. But since I use this library for all of my crypto ATM and since we'll be using this library for the upcoming `bitcoinjs-lib` release, it may make sense to show it some more TLC.

**Comment by jcalfee** [comment]
Thank you.. I understand that `BigInteger("1.1").toString() == "11"` will never work.  It really should truncate or error but it should never convert 1.1 into a number like 11.

Have you used Number.MAX_SAFE_INTEGER?  JavaScript will convert any number higher than MAX_SAFE_INTEGER into MAX_SAFE_INTEGER+1.  So, if you see MAX_SAFE_INTEGER+1 you can assume there was an overflow (even though that may have been a real value).  It works well to have this a bit less than perfect, it is easy to use.  I noticed that in my NodeJS this value was not available.  I ended up just taking the value and putting it in my code so it essentially just runs `if i > 9007199254740991 { throw new Error("Overflow")}`.

It should be very easy to have a function that would error or truncate `if Max.abs(i)!=i {throw new Error("Decimals not supported")` or "Overflow" (above).  The `fromInt` could just error.  If someone needed it later a parameter 2 decimal_detection: "truncate," "round," or the default "error"...

Thanks for sharing your long term plan.  I am in the same boat, several libraries are already using BigInteger.  I'll certainly give `bn.js` some more thought.

**Comment by jprichardson** [comment]
>  It really should truncate or error but it should never convert 1.1 into a number like 11.

Yeah, you're definitely correct here.

> Have you used Number.MAX_SAFE_INTEGER?

No, and only because it's ES6 AFAIK. 

> It should be very easy to have a function that would error or truncate if Math.abs(i)!=i {throw new Error("Decimals not supported") or "Overflow" (above). The fromInt could just error. If someone needed it later a parameter 2 decimal_detection: "truncate," "round," or the default "error"...

Yea, definitely. Gonna keep this issue open as a reminder to take a look at this again.

> I'll certainly give bn.js some more thought.

Yeah, it's definitely fast, and the code is easy to follow. Unfortunately, it's not battle-tested yet . Crazy bugs (https://github.com/indutny/bn.js/issues/45) still come up from time to time that I'm concerned will have subtle effects in crypto applications. This is getting better as Bitcore has depended upon it, so I'm sure within a year or so, it could be considered "battle tested". But `bigi` is based upon `JSBN` that has been around since mid-2000's. I should say, that the author of `bn.js` is very responsive and determined to make `bn.js` a great library and I have no doubt that will eventually be the case.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/cryptocoinjs/bigi/pull/27
